config/routes.rb
Rails.application.routes.draw do

   root 'ads#index'
   resources :ads

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController

  def index
    @ads = Ad.all
  end

  def new
    @ad = Ad.new
  end

  def create
    @ad = Ad.new(ad_params)

    if @ad.save
      flash[:notice]= 'Ad has been created.'
      redirect_to ads_path
    else
      flash.now[:alert]= 'Ad has not been created.'
      render 'new'
    end
  end

  def show
    @ad = Ad.find(params[:id])
  end

  def edit
    @ad = Ad.find(params[:id])
  end

  def update
    @ad = Ad.find(params[:id])
    if @ad.update(ad_params)
      flash[:notice] = 'Ad has been updated.'
      redirect_to ad_path(@ad)
    else
      flash.now[:alert] = 'Ad has not been created.'
      render 'edit'
    end
  end

  def destroy
    @ad = Ad.find(params[:id])

    @ad.destroy
    flash[:notice] = 'Ad has been deleted.'
    redirect_to ads_path
  end

  private

  def ad_params
    params.require(:ad).permit(:name, :description, :email, :img_url, :seller_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ads/_form.html.erb
<%= simple_form_for(@ad) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :email %>
  <%= f.input :img_url, label: 'Image url' %>
  <%= f. submit %>
<% end %>

app/views/ads/edit.html.erb
<h1>Edit <%=@ad.name %></h1>

<%= render 'form', ad: @ad %>

app/views/ads/index.html.erb
<h1>Listing Ads</h1>
<ul>
<% @ads.each do |ad| %>
  <li><%=link_to ad.name, ad %></li>
<% end %>
</ul>
<%= link_to 'New', new_ad_path %>

app/views/ads/new.html.erb
<h1>New</h1>

<%= render 'form' %>

app/views/ads/show.html.erb
<h1><%= @ad.name %></h1>

 <%= link_to 'Edit', edit_ad_path(@ad) %>
 <%= link_to 'Delete', ad_path(@ad), method: :delete, data:[ confirm: 'Are you sure you want to delete this ad?'] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mebay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <% flash.each do |key, message| %>
    <div class="alert alert-<%= key %>">
      <%= message %>
    </div>
  <% end %>
  <%= yield %>
</div>
</body>
</html>